### ISSUE TITLE
Road blocks with different heights

### ISSUE THREAD

**Issue by bubyygh** [derfl007/df-roads#12]
**Is your feature request related to a problem? Please describe.**
It is related to a problem, the slopes. The slopes just don't feel realistic and they're too steep.

**Describe the solution you'd like**
I would like that you can set the height of all road blocks. Slopes would feel much more realistic that way. You could make slopes however you like, steeper or less steep.

**Comment by derfl007** [comment]
I have thought about that, but making the angle of the slopes less steep isn't really possible with json models and I have no intention of changing the models at the moment.

**Comment by bubyygh** [comment]
No, I didn't mean you should change the angle of the slopes. I meant that it would be nice if you could change the height of normal straight road blocks (like snow).

**Comment by derfl007** [comment]
Oh okay I get what you mean, still don't think this will happen for now. I'll keep this open here tho if I change my mind some day.

Also what exactly do you mean by moving the lines from left to right? Normal road lines are centered so I don't really understand what you mean by that
