### ISSUE TITLE
Bug with traffic lights

### ISSUE THREAD

**Issue by Dmitryevich** [derfl007/df-roads#15]
**Describe the bug**
traffic lights are not animated
**To Reproduce**

**Expected behavior**

**Screenshots**

**Version this happens in**
Minecraft:1.12.2
Mod:your roads mod

**Additional context**

**Comment by derfl007** [comment]
So i tried it and it works fine for me, my guess is that you used a static traffic light, please choose the one where it doesn't say Traffic Light (red) but just Traffic Light.
Issue closed!

**Comment by Dmitryevich** [comment]
javaw 2018-11-24 20-23-38-832.avi
<https://drive.google.com/file/d/1qdMuPnLqn_XdH0jUiCvFnwEGNR3slyKq/view?usp=drive_web>


сб, 24 лист. 2018 о 20:29 ДИМЧУК_play ы <antonychev10@gmail.com> пише:

**Comment by derfl007** [comment]
Extremely late reply, but the latest version (made E__Man's Application) has redstone controlled traffic lights, that should fix the problem if you wanna check the mod out again!
