### ISSUE TITLE
Crash on opening world (error with road lanterns)

### ISSUE THREAD

**Issue by derfl007** [derfl007/df-roads#19]
**Describe the bug**
Game crashes due to a bug relating to Road Lanterns (crash report: https://pastebin.com/jfMPkH4P)

**To Reproduce**
Only seems to happen to a few people upon opening a world. Reproduction steps unknown

**Expected behavior**
World should load normally, as it does for most people

**Version this happens in**
Minecraft: 1.12.2
Mod: 1.4+

**Comment by KaiiserAmil** [comment]
IT happened to me on 12 decemeber when i was using this mod and crash my old world everytime could you fix this???

thanks

**Comment by Bbsoto509** [comment]
Updated my Forge, now world with road  lanterns crashes.

[crash-2018-12-28_02.32.25-server.txt](https://github.com/derfl007/df-roads/files/2716037/crash-2018-12-28_02.32.25-server.txt)

**Comment by derfl007** [comment]
So, this might be fixed in the next update, but I'll need some feedback from you guys as I haven't been able to reproduce this error on my PC
