### ISSUE TITLE
Ores instead of Asphalt (Obtaining in survival)

### ISSUE THREAD

**Issue by NightScale5755** [derfl007/df-roads#20]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
Heyo. I was thinking about how you have the tar obtainable in survival at the moment, and I have an idea for an improvement: Ore, that drops an item, whether it be tar, or an item to smelt into tar.

**Additional context**
n/a

**Comment by derfl007** [comment]
I know what you mean, i thought about this, but the thing is that I didn't have an idea on how to make the textures different to coal ore. Do you have any ideas for that?

**Comment by NightScale5755** [comment]
yes. Try taking a look at Bitumen, in the RoadStuff mod 1.7.10. That's where I got the idea.

**Comment by NightScale5755** [comment]
I could make the texture... Possibly...
Let me attempt it, if you want?

**Comment by NightScale5755** [comment]
![bitumen](https://user-images.githubusercontent.com/43540281/49343247-4ebf8100-f62b-11e8-9b35-50c31ff28323.png)
Does this look good?

**Comment by NightScale5755** [comment]
https://www.dropbox.com/s/6m7f9f7lauxaqai/bitumen.png?dl=0

**Comment by NightScale5755** [comment]
btw, I made it in Mcreator.

**Comment by derfl007** [comment]
Looks good, thank you! I'll probably add this in the future

**Comment by NightScale5755** [comment]
No problem.

**Comment by NightScale5755** [comment]
You can go ahead and close the issue now...

**Comment by derfl007** [comment]
Right almost forgot that thanks
