### ISSUE TITLE
Imports not resolved after cloning repository

### ISSUE THREAD

**Issue by E-Mans-Application** [derfl007/df-roads#25]
Hello,

All net imports are not resolved when I clone the repository into Eclipse or IntelliJ.
See https://ibb.co/1vknCyZ
I clone the repository with the URL, then I use "import existing gradle project".

I tried setupDecompWorkspace, but it fails at task :recompileMc with error: NullPointerException (no error message)
Here is the stack trace: https://pastebin.com/eeMtF2uk

I'm not used to cloning GitHub projects, so maybe I'm doing something wrong.
I you know where the issue comes from, could you help me please?

**Comment by derfl007** [comment]
I'm closing the issue, as it isn't related to the mod itself, but feel free to keep commenting for help on cloning the repository
