### ISSUE TITLE
Complete list of road blocks

### ISSUE THREAD

**Issue by ExDomino** [derfl007/df-roads#32]
Hello,

I would like to ask you if I can get a complete list of each road blocks ID added from your mod please ?
Especialy for slopes that are not visible on NEI. And slopes with marks as well.

This is to add your roads in the config of the Ultimate Car Mod in order to make them compatible with cars that will go faster on them.

Thank you in advance.
Ultimate Car Mod : https://minecraft.curseforge.com/projects/ultimate-car-mod
PS : I'm not the author of this mod.

**Comment by derfl007** [comment]
Slopes should use the same id as the normal blocks as their state is determined by whether there is another road block below. So, blocks in slope state should use the same id as in their normal state i think.

**Comment by derfl007** [comment]
So you can try that and tell me if it works, if you still need a list of ids, tell me, but I don't have any more than there are on NEI i guess
