### ISSUE TITLE
Street Lights not working correctly

### ISSUE THREAD

**Issue by ShadowhawkNCFC** [derfl007/df-roads#36]
**Street lights will not work after world is reloaded.**

**To Reproduce**
1. Place a street light
2. Disconnect from world
3. Rejoin
4. The lamp will no longer work.

**Expected behavior**
The lamp to work after reloading

**Version this happens in**
Minecraft: 1.12.2
Mod: v1.5.2

**Comment by derfl007** [comment]
Very late reply, but the latest version (made E__Man's Application) has redstone controlled traffic lights, that should fix the problem
