### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by windmobai** [derfl007/df-roads#37]
Build file 'E:\����\df-roads-master\build.gradle' line: 10

* What went wrong:
A problem occurred evaluating root project 'df-roads-master'.
> 'org.gradle.api.tasks.TaskOutputs org.gradle.api.internal.TaskOutputsInternal.dir(java.lang.Object)'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

I can't build this mod.

**Comment by windmobai** [comment]
刺激

**Comment by derfl007** [comment]
I see you closed this already, did you solve the problem?

**Comment by windmobai** [comment]
> I see you closed this already, did you solve the problem?

Yes, just a network connection problem, gradle didn't fully download forge libs.
