### ISSUE TITLE
Mod uses large amounts of memory

### ISSUE THREAD

**Issue by thetwicher1973** [derfl007/df-roads#7]
when i am loading up minecraft forge and when gets to your mod  my memory goes to 1011/1020
so is there a way to make the memory go down.
i only have 10 mods

**Comment by derfl007** [comment]
I will try to find out what uses the large amounts of RAM, but to play the mod without issues you could try to assign more RAM to Minecraft. For that open the Minecraft Launcher, go to Launch Options, enable Advanced Settings, go to the forge profile, enable JVM Arguments and change -Xmx1G to -Xmx2G (or higher depending on the amount of RAM you have, you shouldn't go above half of your total RAM, so if you have 4GB available assign 2, or if you have 8 assign 4) Then click on Save and start Minecraft

**Comment by derfl007** [comment]
I figured it's probably the high resolution textures that use so much memory, I'll try to make a version with less HD textures and release an HD texture pack or something
