### ISSUE TITLE
Tunnel Sign?

### ISSUE THREAD

**Issue by PowerTurtle** [derfl007/df-roads#8]
Hello, i would like to make a request on a Tunnel Sign. And if you want to, maybe some more danish signs?

https://en.wikipedia.org/wiki/Road_signs_in_Denmark

**Comment by derfl007** [comment]
I'll add the tunnel sign thanks for the suggestion, and about the danish signs: I thought about creating resource packs for different countries. You can do that yourself though, I'll make a template where you can just put in your files with the correct name. I'll make a tutorial on my website and give you the link when I'm done.

**Comment by derfl007** [comment]
I hope this covers everything: https://derfl007.000webhostapp.com/tutorial/custom-road-sign-textures/

**Comment by PowerTurtle** [comment]
I am gonna take a look at it.
I got some more ideas/improvements:
Diagonal Fence?
Sign with lamps pointing from bottom and up on the sign?
Some road construction signs/fence? Maybe concrete barrier?

**Comment by derfl007** [comment]
That's some good ideas thanks very much

**Comment by PowerTurtle** [comment]
Is it possible to add either road textures, or new things on the road blocks, like shark teeth using resources packs?

**Comment by derfl007** [comment]
You can of course change any resources you want, adding new stuff would require changes in the code.
And yes mod textures should override by resource packs

**Comment by derfl007** [comment]
So if you wanted for example yellow street markings, you just need to change the textures and put them in the resource pack

**Comment by PowerTurtle** [comment]
But i would not be able to have both white and yellow on the same time?

**Comment by derfl007** [comment]
Unfortunately no
